version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Running pre-build steps...

  build:
    commands:
      - pwd
      - ls -ltr
      - chmod +x gradlew
      - ./gradlew build

  post_build:
    commands:
      - echo Build completed successfully.
      - pwd
      - ls -ltr

artifacts:
  files:
    - 'build/libs/oltp-*.jar'
  discard-paths: yes

