version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: deploy.sh
      runas: root

  AfterInstall:
    - location: chmod.sh
      runas: root

  ApplicationStart:
    - location: start.sh
      runas: root

